name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: chmod +x ./gradlew clean build

    - name: Run Tests and Generate JaCoCo Report
      run: chmod +x ./gradlew test jacocoTestReport

    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco
        path: build/reports/jacoco/test/html

